In [18]:
import torch
import torch.nn as nn
import pandas as pd
import torch
import torch.nn as nn
import torch.nn.functional as F

In [19]:
class PolicyNet(nn.Module):
    def __init__(self, input_dim: int, hidden=(10,10), output_dim: int = 1,
                 floor_mode: str = "max", min_bid: float = 1e-6):
        super().__init__()
        layers = []
        d = int(input_dim)
        for h in hidden:
            layers += [nn.Linear(d, int(h)), nn.ReLU()]
            d = int(h)
        layers += [nn.Linear(d, int(output_dim))]
        self.net = nn.Sequential(*layers)

        # parámetros “no entrenables” (puedes cambiar por llamada)
        self.floor_mode = floor_mode
        self.min_bid = float(min_bid)

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        """
        Devuelve BID (no raw):
          bid >= 0
          bid >= phi  (si x es phi escalar) o bid >= max_h phi_h (si x es phi vector 24)
        """
        raw = self.net(x).reshape(-1)          # (H,)
        inc = 0.02 * F.softplus(raw)                  # >= 0

        if x.ndim == 2 and x.shape[1] > 1:
            if self.floor_mode == "max":
                floor = x.max(dim=1).values   # (H,)
            elif self.floor_mode == "mean":
                floor = x.mean(dim=1)         # (H,)
            else:
                raise ValueError("floor_mode must be 'max' or 'mean'")
        else:
            floor = x.reshape(-1)             # (H,)

        floor = torch.clamp_min(floor, 0.0)   # >= 0 y >= floor original
        bid = floor + inc + self.min_bid      # >= 0 y >= floor

        return bid                             # (H,)

In [20]:
path_uniform = "symmetric/36redesmedian/nets_best_by_gid_uniform.pt"
saved_nets_uniform = torch.load(path_uniform, map_location="cpu")

gid = 1
net_uniform = PolicyNet(
    input_dim=24,
    hidden=(10,10),
    output_dim=1,
    floor_mode="mean",   # <- igual que en entrenamiento
    min_bid=1e-6         # <- igual que en entrenamiento
)
net_uniform.load_state_dict(saved_nets_uniform[gid], strict=True)
net_uniform.eval() # importante para modo evaluación



path_discriminatory = "symmetric/36redesmedian/nets_best_by_gid_pay_as_bid.pt"
saved_nets_discriminatory = torch.load(path_discriminatory, map_location="cpu")

gid = 1
net_discriminatory = PolicyNet(
    input_dim=24,
    hidden=(10,10),
    output_dim=1,
    floor_mode="mean",   # <- igual que en entrenamiento
    min_bid=1e-6         # <- igual que en entrenamiento
)
net_discriminatory.load_state_dict(saved_nets_discriminatory[gid], strict=True)
net_discriminatory.eval() # importante para modo evaluación

C:\Users\HP\AppData\Local\Temp\ipykernel_6724\1089277082.py:2: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  saved_nets_uniform = torch.load(path_uniform, map_location="cpu")
C:\Users\HP\AppData\Local\Temp\ipykernel_6724\1089277082.py:18: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  saved_nets_discriminatory = torch.load(path_discriminatory, map_location="cpu")

PolicyNet(
  (net): Sequential(
    (0): Linear(in_features=24, out_features=10, bias=True)
    (1): ReLU()
    (2): Linear(in_features=10, out_features=10, bias=True)
    (3): ReLU()
    (4): Linear(in_features=10, out_features=1, bias=True)
  )
)

In [21]:
CSV_PATH = "symmetric/grupos.csv"   # <-- adjust
input = pd.read_csv(CSV_PATH)

In [22]:
input

      id_planta        Fecha       phi  Grupo  precio_d
0             1   2025-04-01  0.083924      1   0.10137
1             2   2025-04-01  0.262222      5   0.28295
2             3   2025-04-01  0.275288      5   0.32637
3             4   2025-04-01  0.260380      5   0.31037
4             5   2025-04-01  0.968472      4   1.02813
...         ...          ...       ...    ...       ...
4207         32   2025-09-09  0.779362      4   0.90894
4208         33   2025-09-09  1.058581      4   1.11735
4209         34   2025-09-09  0.945489      4   1.01274
4210         35   2025-09-09  0.969786      4   1.18348
4211         36   2025-09-09  1.255597      4   1.48540

[4212 rows x 5 columns]

In [23]:
import torch

# Suponiendo que tu DataFrame se llama input
def phi_a_tensor_24(phi_val):
    """Recibe un valor escalar y devuelve un tensor (1,24) duplicado"""
    arr = [phi_val] * 24  # lista de 24 valores iguales
    return torch.tensor([arr], dtype=torch.float)  # shape (1,24)
# Lista para guardar resultados

predicciones_uniform = []
predicciones_discriminatory = []
for i, row in input.iterrows():
    x = phi_a_tensor_24(row['phi'])
    y_pred_uniform = net_uniform(x)
    y_pred_discrimininatoty = net_discriminatory(x)
    predicciones_uniform.append(y_pred_uniform.item())  # convertir de tensor a float
    predicciones_discriminatory.append(y_pred_discrimininatoty.item())

In [24]:
predicciones_uniform

[0.09512508660554886,
 0.2734285891056061,
 0.286495566368103,
 0.2715866267681122,
 0.9796948432922363,
 0.3013453483581543,
 0.10704254359006882,
 0.0968257412314415,
 0.22853077948093414,
 0.24241261184215546,
 0.26769283413887024,
 0.27542468905448914,
 0.2343859225511551,
 0.33771657943725586,
 0.3768555521965027,
 0.8726194500923157,
 0.8790159821510315,
 0.23777641355991364,
 0.5152719020843506,
 0.5037209391593933,
 1.3679075241088867,
 1.1991376876831055,
 0.23777641355991364,
 0.04785288870334625,
 2.3026158809661865,
 0.35653454065322876,
 1.7117218971252441,
 1.6157928705215454,
 0.8421642780303955,
 0.7259947657585144,
 0.7637630701065063,
 0.9197182059288025,
 1.4242277145385742,
 1.4305260181427002,
 1.1289440393447876,
 1.3680684566497803,
 0.08295868337154388,
 0.9578558206558228,
 0.23951295018196106,
 0.23478786647319794,
 0.9842351675033569,
 0.29632818698883057,
 0.10244853794574738,
 0.09546412527561188,
 0.20297570526599884,
 0.2058132141828537,
 0.24792341887950897,
 0.2855866849422455,
 0.19890464842319489,
 0.314666211605072,
 0.36815595626831055,
 0.9020156264305115,
 0.04785288870334625,
 0.04785288870334625,
 0.49574124813079834,
 0.4797276556491852,
 1.1251529455184937,
 1.1885205507278442,
 0.04785288870334625,
 0.31883925199508667,
 2.3134572505950928,
 0.33663588762283325,
 1.7261338233947754,
 1.6288892030715942,
 0.8380999565124512,
 0.6739386320114136,
 0.6971557140350342,
 0.9158173203468323,
 1.4260021448135376,
 1.4302393198013306,
 1.1359754800796509,
 1.3791815042495728,
 0.09523223340511322,
 0.04785288870334625,
 0.29451632499694824,
 0.276929646730423,
 0.9748566150665283,
 0.3004574477672577,
 0.10324590653181076,
 0.08781351894140244,
 0.2353113293647766,
 0.24074885249137878,
 0.26823291182518005,
 0.04785288870334625,
 0.23835690319538116,
 0.3383428752422333,
 0.37598830461502075,
 0.9220685958862305,
 0.4672718346118927,
 0.04785288870334625,
 0.5206277966499329,
 0.5093253254890442,
 1.0706939697265625,
 1.1564909219741821,
 0.16965551674365997,
 0.9578558206558228,
 2.3085269927978516,
 0.3579040765762329,
 1.7213705778121948,
 1.6257781982421875,
 0.8392211198806763,
 0.4449159502983093,
 0.49132832884788513,
 0.9074389338493347,
 1.3101873397827148,
 1.3156019449234009,
 1.0805115699768066,
 1.2524477243423462,
 0.05061228945851326,
 0.1816338151693344,
 0.1870311051607132,
 0.17532037198543549,
 0.9247355461120605,
 0.29563215374946594,
 0.10581134259700775,
 0.08566978573799133,
 0.033331386744976044,
 0.14149296283721924,
 0.23348723351955414,
 0.04785288870334625,
 0.1229289248585701,
 0.3011086583137512,
 0.36773186922073364,
 0.8177863359451294,
 0.1816338151693344,
 1.7006930112838745,
 0.9578558206558228,
 0.44194990396499634,
 1.0613740682601929,
 1.0929617881774902,
 0.9578558206558228,
 0.04785288870334625,
 2.3035337924957275,
 0.31873229146003723,
 1.7171748876571655,
 1.6217769384384155,
 0.7072033882141113,
 0.5169782042503357,
 0.4479736089706421,
 0.8834983110427856,
 1.2920193672180176,
 1.30031156539917,
 1.029592514038086,
 1.3421728610992432,
 0.029608653858304024,
 0.39855140447616577,
 0.15855813026428223,
 0.13293687999248505,
 0.9247463345527649,
 0.2809939980506897,
 0.10138221830129623,
 0.07111766189336777,
 0.1451914757490158,
 0.10920284688472748,
 0.2111903727054596,
 0.22277168929576874,
 0.1110384613275528,
 0.2915247678756714,
 0.33667561411857605,
 0.8380426168441772,
 1.9227583408355713,
 0.16965551674365997,
 0.04785288870334625,
 0.41190633177757263,
 1.0675132274627686,
 1.2268174886703491,
 0.11309050023555756,
 0.8455483317375183,
 2.2955570220947266,
 0.30767613649368286,
 1.6815847158432007,
 1.6041767597198486,
 0.7789129614830017,
 0.7549200654029846,
 0.6348055005073547,
 0.8606704473495483,
 1.2833104133605957,
 1.3128546476364136,
 1.1126500368118286,
 1.3661137819290161,
 0.08204314112663269,
 0.8790159821510315,
 0.24909792840480804,
 0.2324303537607193,
 0.9935477375984192,
 0.29997631907463074,
 0.10578811913728714,
 0.08911321312189102,
 0.16548563539981842,
 0.2076079249382019,
 0.2588859796524048,
 0.2644009292125702,
 0.20734217762947083,
 0.3307701647281647,
 0.3765175938606262,
 0.877250075340271,
 0.1816338151693344,
 1.7239603996276855,
 1.7006930112838745,
 0.4883064925670624,
 1.0882834196090698,
 1.1958703994750977,
 0.04785288870334625,
 0.7225772738456726,
 2.2863409519195557,
 0.3519112765789032,
 1.6956969499588013,
 1.6096916198730469,
 0.8313853740692139,
 0.7737109065055847,
 0.7093780040740967,
 0.9117926955223083,
 1.3350250720977783,
 1.3424352407455444,
 1.1181851625442505,
 1.3368027210235596,
 0.08200807869434357,
 0.04785288870334625,
 0.23178119957447052,
 0.2139357626438141,
 0.9761492013931274,
 0.3033054769039154,
 0.10902877151966095,
 0.08177950978279114,
 0.17696505784988403,
 0.1840105652809143,
 0.25289255380630493,
 0.2589729428291321,
 0.1838066279888153,
 0.32135942578315735,
 0.37816306948661804,
 0.8869718909263611,
 1.9227583408355713,
 0.4716142416000366,
 0.5019356608390808,
 1.9227583408355713,
 1.108424186706543,
 1.193504810333252,
 0.23777641355991364,
 0.9578558206558228,
 2.2982187271118164,
 0.34050998091697693,
 1.7096537351608276,
 1.6208094358444214,
 0.7857646346092224,
 0.7971584796905518,
 0.6560492515563965,
 0.8947475552558899,
 1.3204827308654785,
 1.330795168876648,
 1.1771583557128906,
 1.2956806421279907,
 0.08505329489707947,
 0.2734285891056061,
 0.19646213948726654,
 0.14191868901252747,
 0.9627854824066162,
 0.3000278174877167,
 0.1053086668252945,
 0.07886070758104324,
 0.19333699345588684,
 0.13619202375411987,
 0.24542854726314545,
 0.24858596920967102,
 0.13380372524261475,
 0.31695738434791565,
 0.3733144998550415,
 0.9133427143096924,
 0.2734285891056061,
 1.9227583408355713,
 0.47732269763946533,
 1.7006930112838745,
 1.0655841827392578,
 1.215577244758606,
 0.16965551674365997,
 0.9357962608337402,
 2.2744290828704834,
 0.3384859263896942,
 1.712204098701477,
 1.578535556793213,
 0.8043590784072876,
 0.8377755880355835,
 0.7671184539794922,
 0.8896171450614929,
 1.3477380275726318,
 1.3553215265274048,
 1.079827904701233,
 1.3139832019805908,
 0.0820959135890007,
 0.39855140447616577,
 0.2913028299808502,
 0.25878721475601196,
 1.029878854751587,
 0.3044481873512268,
 0.11107590794563293,
 0.1079021692276001,
 0.21213391423225403,
 0.22170935571193695,
 0.2704311013221741,
 0.27995556592941284,
 0.2254149615764618,
 0.34164997935295105,
 0.3823712468147278,
 0.9379679560661316,
 0.04785288870334625,
 0.23777641355991364,
 0.5272184610366821,
 1.7006930112838745,
 1.1795679330825806,
 1.2406609058380127,
 0.16965551674365997,
 0.9540004134178162,
 2.319955587387085,
 0.3620656132698059,
 1.733442783355713,
 1.6430792808532715,
 0.8637644052505493,
 0.8071569204330444,
 0.7324976325035095,
 0.9399963021278381,
 1.391903281211853,
 1.397680640220642,
 1.164297342300415,
 1.4088139533996582,
 0.036608632653951645,
 0.011200523003935814,
 0.20358167588710785,
 0.15942686796188354,
 0.9653127789497375,
 0.27789855003356934,
 0.9612544775009155,
 0.06934963911771774,
 0.15312209725379944,
 0.12552039325237274,
 0.21005690097808838,
 0.22382406890392303,
 0.14922723174095154,
 0.2964085340499878,
 0.34418630599975586,
 0.8769077658653259,
 0.4672718346118927,
 0.9578558206558228,
 0.4613063931465149,
 0.4137286841869354,
 1.1119086742401123,
 1.230389952659607,
 0.11309050023555756,
 0.9367650151252747,
 2.281944751739502,
 0.31923776865005493,
 1.704872965812683,
 1.6092549562454224,
 0.8037927746772766,
 0.7351654767990112,
 0.6641165614128113,
 0.8729879260063171,
 1.2302895784378052,
 1.233605980873108,
 1.109513521194458,
 1.3733924627304077,
 0.06451858580112457,
 0.35819557309150696,
 0.20741894841194153,
 0.2124023735523224,
 0.9413504004478455,
 0.2911383807659149,
 0.9500623941421509,
 0.04340847581624985,
 0.13029232621192932,
 0.1687065213918686,
 0.23503276705741882,
 0.23724393546581268,
 0.18233999609947205,
 0.30657076835632324,
 0.35973110795021057,
 0.8634993433952332,
 0.8790159821510315,
 1.9227583408355713,
 0.48128509521484375,
 0.4641425609588623,
 1.028264045715332,
 1.1821990013122559,
 0.23777641355991364,
 0.8455483317375183,
 2.257465362548828,
 0.3266938030719757,
 1.6633118391036987,
 1.5661417245864868,
 0.7837279438972473,
 0.6272081732749939,
 0.3490692675113678,
 0.8355970978736877,
 1.2087335586547852,
 1.2115238904953003,
 1.0538697242736816,
 1.3186352252960205,
 0.0613211914896965,
 0.37864407896995544,
 0.18310482800006866,
 0.16727882623672485,
 0.9738112092018127,
 0.29260867834091187,
 0.9685745239257812,
 0.09007088840007782,
 0.14124329388141632,
 0.14113132655620575,
 0.2095082700252533,
 0.21052077412605286,
 0.13273295760154724,
 0.2776535153388977,
 0.35623952746391296,
 0.8425149917602539,
 0.9578558206558228,
 0.16965551674365997,
 0.47841155529022217,
 0.4542370140552521,
 1.1311883926391602,
 1.1500381231307983,
 0.9578558206558228,
 0.9578558206558228,
 2.3122880458831787,
 0.2986493706703186,
 1.7233976125717163,
 1.6327506303787231,
 0.7914440631866455,
 0.5529119372367859,
 0.3518978953361511,
 0.8997265100479126,
 1.0656641721725464,
 1.0722934007644653,
 1.0922267436981201,
 1.3792221546173096,
 0.07265633344650269,
 0.0876697450876236,
 0.25202298164367676,
 0.23098541796207428,
 0.9752050638198853,
 0.2844164967536926,
 0.10629485547542572,
 0.9110308885574341,
 0.19852539896965027,
 0.19238033890724182,
 0.23635081946849823,
 0.2470652461051941,
 0.201018825173378,
 0.3131225109100342,
 0.3537789285182953,
 0.8215711116790771,
 2.214876413345337,
 0.9578558206558228,
 0.5197834968566895,
 0.509119987487793,
 1.0817017555236816,
 1.1955276727676392,
 0.04785288870334625,
 0.7225772738456726,
 2.301751136779785,
 0.3293125331401825,
 1.698482871055603,
 1.6114790439605713,
 0.8137531280517578,
 0.8198785781860352,
 0.5633774399757385,
 0.9017390608787537,
 0.9715600609779358,
 0.9869785904884338,
 1.1098461151123047,
 1.3291903734207153,
 0.03424828499555588,
 0.06555674225091934,
 0.16757795214653015,
 0.12408801913261414,
 0.9269989132881165,
 0.28447264432907104,
 0.10158342123031616,
 0.8939731121063232,
 0.12048826366662979,
 0.11881454288959503,
 0.19691257178783417,
 0.2855866849422455,
 0.1121056005358696,
 0.26455286145210266,
 0.34498801827430725,
 0.7656846642494202,
 0.9578558206558228,
 1.7239603996276855,
 0.46120280027389526,
 0.4882422983646393,
 1.063785433769226,
 1.2156507968902588,
 0.04785288870334625,
 0.04785288870334625,
 2.2848033905029297,
 0.28192779421806335,
 1.6547919511795044,
 1.5743334293365479,
 0.7978121638298035,
 0.6013320088386536,
 0.6930931806564331,
 0.8619085550308228,
 1.049049735069275,
 1.0631556510925293,
 1.1107779741287231,
 1.3593487739562988,
 0.06350169330835342,
 0.08540353924036026,
 0.19058823585510254,
 0.18274062871932983,
 0.8922238945960999,
 0.2933658957481384,
 0.08240525424480438,
 0.9035049080848694,
 0.13072185218334198,
 0.17038652300834656,
 0.24681904911994934,
 0.9578558206558228,
 0.1641424596309662,
 0.30946898460388184,
 0.36192402243614197,
 0.7788990139961243,
 1.9227583408355713,
 0.04785288870334625,
 0.40824589133262634,
 1.7239603996276855,
 0.8910713791847229,
 1.1786580085754395,
 0.11309050023555756,
 0.7181574106216431,
 2.089566230773926,
 0.3340347707271576,
 1.6596978902816772,
 1.5860004425048828,
 0.7979397773742676,
 0.5697746276855469,
 0.34353306889533997,
 0.8724199533462524,
 1.038233757019043,
 1.0686861276626587,
 1.051781415939331,
 1.2873958349227905,
 0.04828070476651192,
 0.09858281910419464,
 0.1401490867137909,
 0.15166278183460236,
 0.8719521760940552,
 0.28788483142852783,
 0.11005916446447372,
 0.9210497736930847,
 0.09182631224393845,
 0.11166152358055115,
 0.22075356543064117,
 0.7225772738456726,
 0.1409032940864563,
 0.2919248044490814,
 0.35962098836898804,
 0.7800997495651245,
 2.214876413345337,
 1.7006930112838745,
 0.39149489998817444,
 0.4716142416000366,
 1.1104761362075806,
 1.1376699209213257,
 0.23777641355991364,
 0.7229639291763306,
 2.1325840950012207,
 0.30817320942878723,
 0.011200523003935814,
 0.9357962608337402,
 0.6829543113708496,
 0.4432319700717926,
 0.18045781552791595,
 0.9139999747276306,
 1.107943058013916,
 1.1102904081344604,
 1.0675971508026123,
 1.3597441911697388,
 0.07911454141139984,
 0.1816338151693344,
 0.211634561419487,
 0.14761151373386383,
 0.9570962190628052,
 0.2980023920536041,
 0.09250860661268234,
 0.9121586680412292,
 0.15232190489768982,
 0.1344144642353058,
 0.2489469200372696,
 0.7225772738456726,
 0.14162050187587738,
 0.3215307891368866,
 0.37115639448165894,
 0.8458985686302185,
 0.4672718346118927,
 0.23777641355991364,
 0.43724867701530457,
 0.04785288870334625,
 0.9961803555488586,
 1.2138071060180664,
 0.9578558206558228,
 0.7225772738456726,
 2.0441668033599854,
 0.3417758643627167,
 1.7088404893875122,
 0.3575372099876404,
 0.7861006259918213,
 0.6902430057525635,
 0.5232354998588562,
 0.9089056849479675,
 1.0789130926132202,
 1.0842100381851196,
 1.031085729598999,
 1.249646544456482,
 0.08105313777923584,
 0.9578558206558228,
 0.2878299653530121,
 0.24820448458194733,
 1.0280663967132568,
 0.3043099343776703,
 0.9440019130706787,
 0.9411157965660095,
 0.1951340287923813,
 0.21535144746303558,
 0.26984864473342896,
 0.25365713238716125,
 0.22779212892055511,
 0.3406837284564972,
 0.38215428590774536,
 0.8575088381767273,
 0.8629534840583801,
 0.4716142416000366,
 0.5372371673583984,
 1.9227583408355713,
 1.154529333114624,
 1.2350306510925293,
 0.16965551674365997,
 0.9578558206558228,
 2.13606333732605,
 0.36107125878334045,
 1.734222412109375,
 1.9721171855926514,
 0.8608303666114807,
 0.6514491438865662,
 0.4617864489555359,
 0.9509140253067017,
 1.1229192018508911,
 1.1302698850631714,
 1.1654245853424072,
 1.407563328742981,
 0.07733239978551865,
 1.9227583408355713,
 0.29777416586875916,
 0.2344733327627182,
 1.0395690202713013,
 0.30608251690864563,
 0.1116931140422821,
 0.9436394572257996,
 0.22024832665920258,
 0.1808609515428543,
 0.27059200406074524,
 0.2827188968658447,
 0.2261240929365158,
 0.3439882695674896,
 0.3851771950721741,
 0.8886107206344604,
 0.2734285891056061,
 1.9721171855926514,
 0.5484795570373535,
 0.5478936433792114,
 1.0800836086273193,
 0.6467800140380859,
 0.7182168364524841,
 0.04785288870334625,
 2.141636848449707,
 0.3648609519004822,
 1.7374398708343506,
 1.646638035774231,
 0.8766927123069763,
 0.3159864842891693,
 0.24050316214561462,
 0.9548613429069519,
 1.223137378692627,
 1.229745864868164,
 1.1809041500091553,
 1.418194055557251,
 0.08368612080812454,
 0.2734285891056061,
 0.2640797197818756,
 0.21262221038341522,
 0.994847297668457,
 0.3007732629776001,
 0.1026720404624939,
 0.9276753067970276,
 0.1426512897014618,
 0.17937332391738892,
 0.2612982392311096,
 0.26982054114341736,
 0.2009594887495041,
 0.32740065455436707,
 0.37642258405685425,
 0.8191046118736267,
 0.8790159821510315,
 1.9337984323501587,
 0.4971539080142975,
 0.5237034559249878,
 0.8401898741722107,
 1.9227583408355713,
 0.7046841382980347,
 0.8455483317375183,
 2.1120917797088623,
 0.3479299247264862,
 1.721044898033142,
 1.627253532409668,
 0.8163986802101135,
 0.6427471041679382,
 0.7238956093788147,
 0.9274179935455322,
 1.1984702348709106,
 1.2055493593215942,
 1.0625684261322021,
 1.303124189376831,
 0.07362040877342224,
 0.8790159821510315,
 0.16677843034267426,
 0.14872561395168304,
 0.9113652110099792,
 0.3029470443725586,
 0.10866151005029678,
 0.921681821346283,
 0.17546246945858002,
 0.10158421099185944,
 0.24357326328754425,
 0.2469814121723175,
 0.13974148035049438,
 0.3142462968826294,
 0.37627410888671875,
 0.8335049748420715,
 0.04785288870334625,
 1.9171465635299683,
 0.43979400396347046,
 0.4612380266189575,
 0.673338770866394,
 0.04785288870334625,
 0.6999827027320862,
 0.04785288870334625,
 2.1231212615966797,
 0.33297836780548096,
 1.72979736328125,
 1.635851502418518,
 0.7360683679580688,
 0.6488974690437317,
 0.719352662563324,
 0.8975881934165955,
 1.1781989336013794,
 1.1809941530227661,
 0.946548342704773,
 1.2117587327957153,
 0.07824532687664032,
 0.04785288870334625,
 0.28978821635246277,
 0.22930146753787994,
 1.0001991987228394,
 0.28821682929992676,
 0.09737865626811981,
 0.9259016513824463,
 0.2458195984363556,
 0.1886621117591858,
 0.257002055644989,
 0.26582157611846924,
 0.20953141152858734,
 0.3330632448196411,
 0.37286683917045593,
 0.8619248270988464,
 0.1816338151693344,
 1.9508569240570068,
 0.5258012413978577,
 0.5069898366928101,
 0.8189610838890076,
 1.9227583408355713,
 0.7027341723442078,
 0.16965551674365997,
 2.11519718170166,
 0.353486031293869,
 1.7166942358016968,
 1.6216250658035278,
 0.8000020980834961,
 0.7199716567993164,
 0.8053905367851257,
 0.9297622442245483,
 1.196768879890442,
 1.201942801475525,
 1.0937087535858154,
 1.334731936454773,
 0.07624699920415878,
 0.09751249849796295,
 0.2825607657432556,
 0.2222861647605896,
 0.9721618294715881,
 0.2925834655761719,
 0.10625617206096649,
 0.9006174802780151,
 0.21386225521564484,
 0.16395461559295654,
 0.259414404630661,
 0.26828843355178833,
 0.20964789390563965,
 0.33631590008735657,
 0.37845179438591003,
 0.8590401411056519,
 0.8790159821510315,
 1.9644056558609009,
 0.534793496131897,
 0.5176156759262085,
 0.8761066198348999,
 0.23777641355991364,
 0.8332099318504333,
 0.23777641355991364,
 2.1352689266204834,
 0.35680025815963745,
 1.7306216955184937,
 1.639793038368225,
 0.8218132853507996,
 0.6518637537956238,
 0.6737390160560608,
 0.9479212164878845,
 1.2074835300445557,
 1.2142139673233032,
 1.1625398397445679,
 1.4779707193374634,
 0.07098764181137085,
 0.09404628723859787,
 0.2936233878135681,
 0.22783087193965912,
 0.9515495896339417,
 0.29366233944892883,
 0.1075645163655281,
 0.9018604755401611,
 0.23613323271274567,
 0.17178021371364594,
 0.26150843501091003,
 0.2719130516052246,
 0.20917390286922455,
 0.3393714129924774,
 0.38030266761779785,
 0.8770240545272827,
 0.9578558206558228,
 1.9677767753601074,
 0.5466521382331848,
 0.5284728407859802,
 0.89834064245224,
 0.16965551674365997,
 0.8340921998023987,
 0.9578558206558228,
 2.137982130050659,
 0.3600842356681824,
 1.7325129508972168,
 1.6416884660720825,
 0.8373045921325684,
 0.33500853180885315,
 0.30218619108200073,
 0.9500385522842407,
 1.2205095291137695,
 1.2270407676696777,
 1.176530122756958,
 1.4854998588562012,
 0.07628411054611206,
 0.09043107181787491,
 0.2580639719963074,
 0.2214137464761734,
 0.9054450988769531,
 0.28688740730285645,
 0.8790159821510315,
 0.880296528339386,
 0.14620336890220642,
 0.16514846682548523,
 0.24316687881946564,
 0.25273847579956055,
 0.2008490413427353,
 0.3181212544441223,
 0.3657739758491516,
 0.7739207148551941,
 0.04785288870334625,
 1.9049679040908813,
 0.5097736716270447,
 0.4951867461204529,
 0.7974344491958618,
 0.6467800140380859,
 0.8072202801704407,
 0.23777641355991364,
 2.115168809890747,
 0.3372270166873932,
 1.6386457681655884,
 1.7221673727035522,
 0.7913262844085693,
 0.5869242548942566,
 0.6755592226982117,
 0.9181867837905884,
 1.1092520952224731,
 1.1189876794815063,
 1.0818802118301392,
 1.398680329322815,
 0.07752939313650131,
 0.10757192969322205,
 0.2223450392484665,
 0.2282017469406128,
 0.9056845307350159,
 0.29132890701293945,
 1.9227583408355713,
 0.8903753757476807,
 0.07840749621391296,
 0.16233614087104797,
 0.2532069683074951,
 0.26063573360443115,
 0.19017988443374634,
 0.33129680156707764,
 0.37620896100997925,
 0.7996006608009338,
 0.2734285891056061,
 1.9397695064544678,
 0.5113244652748108,
 0.5011747479438782,
 0.8082725405693054,
 0.4716142416000366,
 0.8208341598510742,
 0.04785288870334625,
 2.126324415206909,
 0.35124579071998596,
 1.6556769609451294,
 1.7413315773010254,
 0.786199688911438,
 0.58083176612854,
 0.6229889988899231,
 0.9292727708816528,
 1.1156611442565918,
 1.1228801012039185,
 1.0449175834655762,
 1.400093913078308,
 0.07781167328357697,
 0.10756853967905045,
 0.20567412674427032,
 0.1897093951702118,
 0.8953902721405029,

In [25]:
predicciones_discriminatory

[0.09697728604078293,
 0.2752673327922821,
 0.28833338618278503,
 0.27342551946640015,
 0.9814954400062561,
 0.30318230390548706,
 0.10889395326375961,
 0.09867782890796661,
 0.23037338256835938,
 0.24425402283668518,
 0.26953205466270447,
 0.27726325392723083,
 0.23622801899909973,
 0.33955079317092896,
 0.3786875903606415,
 0.8744255900382996,
 0.8808217644691467,
 0.2396182268857956,
 0.5170966982841492,
 0.5055463314056396,
 1.3697011470794678,
 1.2009345293045044,
 0.2396182268857956,
 0.049708135426044464,
 2.3043510913848877,
 0.3583676218986511,
 1.7135028839111328,
 1.6175789833068848,
 0.8439719676971436,
 0.7278085350990295,
 0.7655748724937439,
 0.9215219020843506,
 1.4260202646255493,
 1.4323184490203857,
 1.1307423114776611,
 1.3698620796203613,
 0.08481168746948242,
 0.9596575498580933,
 0.24135461449623108,
 0.23662994801998138,
 0.9860357046127319,
 0.2981654405593872,
 0.10430025309324265,
 0.09731630980968475,
 0.20482052862644196,
 0.20765778422355652,
 0.2497643530368805,
 0.28742456436157227,
 0.20074975490570068,
 0.31650227308273315,
 0.36998844146728516,
 0.9038202166557312,
 0.049708135426044464,
 0.049708135426044464,
 0.4975670576095581,
 0.4815542995929718,
 1.1269512176513672,
 1.1903176307678223,
 0.049708135426044464,
 0.32067495584487915,
 2.3151917457580566,
 0.3384701609611511,
 1.7279138565063477,
 1.6306747198104858,
 0.8399079442024231,
 0.6757551431655884,
 0.6989709734916687,
 0.9176211953163147,
 1.4277946949005127,
 1.4320317506790161,
 1.1377735137939453,
 1.3809750080108643,
 0.0970844179391861,
 0.049708135426044464,
 0.29635366797447205,
 0.2787680923938751,
 0.9766574501991272,
 0.30229446291923523,
 0.10509756952524185,
 0.0896662026643753,
 0.23715335130691528,
 0.24259041249752045,
 0.2700721025466919,
 0.049708135426044464,
 0.24019867181777954,
 0.3401770293712616,
 0.37782037258148193,
 0.923872172832489,
 0.46909913420677185,
 0.049708135426044464,
 0.5224523544311523,
 0.5111504793167114,
 1.072493314743042,
 1.158288598060608,
 0.1715027242898941,
 0.9596575498580933,
 2.3102619647979736,
 0.3597370982170105,
 1.7231509685516357,
 1.6275638341903687,
 0.8410289883613586,
 0.446744441986084,
 0.493154376745224,
 0.9092432260513306,
 1.3119820356369019,
 1.317396640777588,
 1.082310676574707,
 1.2542436122894287,
 0.052467428147792816,
 0.1834801584482193,
 0.18887707591056824,
 0.1771671622991562,
 0.9265389442443848,
 0.29746943712234497,
 0.10766283422708511,
 0.08752261102199554,
 0.03518680855631828,
 0.14334209263324738,
 0.23532940447330475,
 0.049708135426044464,
 0.12477929145097733,
 0.302945613861084,
 0.36956435441970825,
 0.8195953369140625,
 0.1834801584482193,
 1.7024747133255005,
 0.9596575498580933,
 0.44377854466438293,
 1.0631736516952515,
 1.0947606563568115,
 0.9596575498580933,
 0.049708135426044464,
 2.3052690029144287,
 0.3205680251121521,
 1.7189555168151855,
 1.6235628128051758,
 0.7090181708335876,
 0.5188029408454895,
 0.4498019218444824,
 0.8853039145469666,
 1.2938144207000732,
 1.302106499671936,
 1.0313924551010132,
 1.3439669609069824,
 0.0314641147851944,
 0.40038228034973145,
 0.16040611267089844,
 0.13478657603263855,
 0.9265497326850891,
 0.28283214569091797,
 0.10323400795459747,
 0.07297144830226898,
 0.14704038202762604,
 0.11105411499738693,
 0.2130344808101654,
 0.22461479902267456,
 0.1128896176815033,
 0.2933622896671295,
 0.3385098874568939,
 0.8398506045341492,
 1.924526333808899,
 0.1715027242898941,
 0.049708135426044464,
 0.4137365221977234,
 1.069312572479248,
 1.2286138534545898,
 0.11494151502847672,
 0.8473559021949768,
 2.297292947769165,
 0.3095127046108246,
 1.683367371559143,
 1.6059634685516357,
 0.7807239890098572,
 0.7567323446273804,
 0.6366240382194519,
 0.8624772429466248,
 1.285105586051941,
 1.3146493434906006,
 1.1144486665725708,
 1.3679075241088867,
 0.083896204829216,
 0.8808217644691467,
 0.2509387731552124,
 0.23427262902259827,
 0.9953481554985046,
 0.3018133342266083,
 0.1076396182179451,
 0.09096580743789673,
 0.16733312606811523,
 0.20945234596729279,
 0.2607259750366211,
 0.2662404477596283,
 0.2091866284608841,
 0.33260491490364075,
 0.378349632024765,
 0.8790559768676758,
 0.1834801584482193,
 1.725740671157837,
 1.7024747133255005,
 0.4901326894760132,
 1.0900824069976807,
 1.1976673603057861,
 0.049708135426044464,
 0.7243912816047668,
 2.2880775928497314,
 0.35374465584754944,
 1.6974788904190063,
 1.6114780902862549,
 0.8331936597824097,
 0.7755221724510193,
 0.7111926674842834,
 0.9135968089103699,
 1.3368192911148071,
 1.3442293405532837,
 1.1199835538864136,
 1.3385969400405884,
 0.08386114239692688,
 0.049708135426044464,
 0.23362351953983307,
 0.2157796323299408,
 0.9779499173164368,
 0.3051423132419586,
 0.1108800545334816,
 0.08363258838653564,
 0.17881174385547638,
 0.18585672974586487,
 0.25473305583000183,
 0.2608129382133484,
 0.18565282225608826,
 0.3231949508190155,
 0.3799950182437897,
 0.8887773156166077,
 1.924526333808899,
 0.47344133257865906,
 0.5037611722946167,
 1.924526333808899,
 1.1102228164672852,
 1.19530189037323,
 0.2396182268857956,
 0.9596575498580933,
 2.299954414367676,
 0.3423440158367157,
 1.7114348411560059,
 1.6225953102111816,
 0.7875753045082092,
 0.7989685535430908,
 0.6578667163848877,
 0.896552562713623,
 1.322277307510376,
 1.3325895071029663,
 1.1789555549621582,
 1.2974755764007568,
 0.08690615743398666,
 0.2752673327922821,
 0.19830742478370667,
 0.1437678039073944,
 0.9645869135856628,
 0.3018648326396942,
 0.10716019570827484,
 0.08071398735046387,
 0.19518250226974487,
 0.13804151117801666,
 0.24726969003677368,
 0.25042685866355896,
 0.13565337657928467,
 0.31879323720932007,
 0.37514668703079224,
 0.9151467084884644,
 0.2752673327922821,
 1.924526333808899,
 0.4791494905948639,
 1.7024747133255005,
 1.0673836469650269,
 1.2173737287521362,
 0.1715027242898941,
 0.9375990629196167,
 2.2761669158935547,
 0.34032008051872253,
 1.7139850854873657,
 1.5803232192993164,
 0.806168794631958,
 0.8395835757255554,
 0.7689301371574402,
 0.89142245054245,
 1.3495320081710815,
 1.357115387916565,
 1.0816270112991333,
 1.3157778978347778,
 0.08394896984100342,
 0.40038228034973145,
 0.29314035177230835,
 0.26062721014022827,
 1.0316787958145142,
 0.30628496408462524,
 0.11292704939842224,
 0.10975352674722672,
 0.21397793292999268,
 0.22355255484580994,
 0.2722700834274292,
 0.2817937731742859,
 0.2272578328847885,
 0.34348395466804504,
 0.3842029869556427,
 0.9397706985473633,
 0.049708135426044464,
 0.2396182268857956,
 0.5290426015853882,
 1.7024747133255005,
 1.1813652515411377,
 1.2424569129943848,
 0.1715027242898941,
 0.955802321434021,
 2.3216896057128906,
 0.3638983964920044,
 1.7352224588394165,
 1.6448640823364258,
 0.8655710220336914,
 0.8089665174484253,
 0.7343111038208008,
 0.9417989253997803,
 1.3936965465545654,
 1.3994736671447754,
 1.1660947799682617,
 1.410606861114502,
 0.0384640246629715,
 0.01305479183793068,
 0.2054264396429062,
 0.16127479076385498,
 0.9671140909194946,
 0.2797369062900543,
 0.9630559682846069,
 0.07120354473590851,
 0.1549704670906067,
 0.12737059593200684,
 0.21190111339092255,
 0.2256670892238617,
 0.15107585489749908,
 0.29824575781822205,
 0.3460201323032379,
 0.8787136673927307,
 0.46909913420677185,
 0.9596575498580933,
 0.4631339907646179,
 0.415558785200119,
 1.113707184791565,
 1.232186198234558,
 0.11494151502847672,
 0.9385678172111511,
 2.283681869506836,
 0.321073442697525,
 1.7066543102264404,
 1.6110414266586304,
 0.805602490901947,
 0.7369787693023682,
 0.6659336090087891,
 0.8747940063476562,
 1.2320858240127563,
 1.235402226448059,
 1.1113120317459106,
 1.3751859664916992,
 0.066372811794281,
 0.36002856492996216,
 0.2092633992433548,
 0.21424637734889984,
 0.9431529641151428,
 0.29297590255737305,
 0.95186448097229,
 0.04526379331946373,
 0.13214220106601715,
 0.1705537885427475,
 0.23687481880187988,
 0.23908579349517822,
 0.18418629467487335,
 0.30840739607810974,
 0.361564040184021,
 0.8653059601783752,
 0.8808217644691467,
 1.924526333808899,
 0.4831116497516632,
 0.4659700095653534,
 1.0300639867782593,
 1.1839962005615234,
 0.2396182268857956,
 0.8473559021949768,
 2.259204626083374,
 0.32852888107299805,
 1.6650956869125366,
 1.5679298639297485,
 0.7855387330055237,
 0.6290271282196045,
 0.350902795791626,
 0.8374052047729492,
 1.2105302810668945,
 1.2133204936981201,
 1.0556694269180298,
 1.320429801940918,
 0.06317562609910965,
 0.3804759979248047,
 0.1849510669708252,
 0.16912619769573212,
 0.9756121039390564,
 0.2944461405277252,
 0.970375657081604,
 0.09192342311143875,
 0.14309245347976685,
 0.14298048615455627,
 0.21135252714157104,
 0.21236494183540344,
 0.13458266854286194,
 0.2794918715953827,
 0.3580726385116577,
 0.844322681427002,
 0.9596575498580933,
 0.1715027242898941,
 0.48023825883865356,
 0.45606499910354614,
 1.1329865455627441,
 1.1518359184265137,
 0.9596575498580933,
 0.9596575498580933,
 2.3140227794647217,
 0.3004864752292633,
 1.7251778841018677,
 1.6345360279083252,
 0.7932544350624084,
 0.5547347664833069,
 0.35373127460479736,
 0.9015312194824219,
 1.0674636363983154,
 1.0740926265716553,
 1.0940256118774414,
 1.381015658378601,
 0.07451002299785614,
 0.08952243626117706,
 0.2538635730743408,
 0.2328278124332428,
 0.9770058393478394,
 0.2862544655799866,
 0.10814632475376129,
 0.9128350019454956,
 0.20037053525447845,
 0.19422592222690582,
 0.23819275200366974,
 0.24890625476837158,
 0.20286378264427185,
 0.31495869159698486,
 0.355612188577652,
 0.8233799338340759,
 2.2166194915771484,
 0.9596575498580933,
 0.5216080546379089,
 0.5109450817108154,
 1.083500862121582,
 1.1973246335983276,
 0.049708135426044464,
 0.7243912816047668,
 2.3034865856170654,
 0.3311474025249481,
 1.7002646923065186,
 1.6132653951644897,
 0.8155623078346252,
 0.8216874599456787,
 0.5651997327804565,
 0.9035436511039734,
 0.973361074924469,
 0.9887790679931641,
 1.1116446256637573,
 1.3309847116470337,
 0.03610369563102722,
 0.0674108937382698,
 0.16942529380321503,
 0.1259383112192154,
 0.9288021922111511,
 0.286310613155365,
 0.10343519598245621,
 0.8957781195640564,
 0.12233878672122955,
 0.12066517770290375,
 0.1987578272819519,
 0.28742456436157227,
 0.11395668238401413,
 0.26639237999916077,
 0.34682178497314453,
 0.7674963474273682,
 0.9596575498580933,
 1.725740671157837,
 0.4630303978919983,
 0.4900684952735901,
 1.0655848979949951,
 1.217447280883789,
 0.049708135426044464,
 0.049708135426044464,
 2.2865402698516846,
 0.28376588225364685,
 1.6565762758255005,
 1.576121211051941,
 0.7996222376823425,
 0.6031522750854492,
 0.6949086785316467,
 0.8637152314186096,
 1.0508495569229126,
 1.0649551153182983,
 1.1125764846801758,
 1.3611425161361694,
 0.06535597890615463,
 0.08725637942552567,
 0.1924339383840561,
 0.18458689749240875,
 0.8940290212631226,
 0.295203298330307,
 0.0842582955956459,
 0.9053094387054443,
 0.13257169723510742,
 0.1722336709499359,
 0.24866007268428802,
 0.9596575498580933,
 0.16599005460739136,
 0.311305433511734,
 0.36375680565834045,
 0.7807100415229797,
 1.924526333808899,
 0.049708135426044464,
 0.4100762903690338,
 1.725740671157837,
 0.8928765654563904,
 1.180455207824707,
 0.11494151502847672,
 0.7199715971946716,
 2.0913197994232178,
 0.3358692526817322,
 1.6614819765090942,
 1.5877877473831177,
 0.7997498512268066,
 0.5715965628623962,
 0.3453669250011444,
 0.8742261528968811,
 1.0400336980819702,
 1.0704854726791382,
 1.0535811185836792,
 1.2891910076141357,
 0.050135936588048935,
 0.1004347950220108,
 0.1419983059167862,
 0.15351124107837677,
 0.8737583756446838,
 0.2897225618362427,
 0.111910380423069,
 0.922853410243988,
 0.09367872774600983,
 0.11351263523101807,
 0.22259683907032013,
 0.7243912816047668,
 0.1427524834871292,
 0.29376232624053955,
 0.36145392060279846,
 0.7819107174873352,
 2.2166194915771484,
 1.7024747133255005,
 0.39332613348960876,
 0.47344133257865906,
 1.1122746467590332,
 1.1394679546356201,
 0.2396182268857956,
 0.72477787733078,
 2.134334087371826,
 0.31000974774360657,
 0.01305479183793068,
 0.9375990629196167,
 0.6847703456878662,
 0.44506052136421204,
 0.182304248213768,
 0.9158039689064026,
 1.1097416877746582,
 1.112088918685913,
 1.0693964958190918,
 1.3615379333496094,
 0.08096779882907867,
 0.1834801584482193,
 0.21347862482070923,
 0.14946025609970093,
 0.9588979482650757,
 0.2998395264148712,
 0.09436097741127014,
 0.9139627814292908,
 0.15417033433914185,
 0.13626407086849213,
 0.25078776478767395,
 0.7243912816047668,
 0.14346963167190552,
 0.32336631417274475,
 0.3729887306690216,
 0.8477060794830322,
 0.46909913420677185,
 0.2396182268857956,
 0.43907755613327026,
 0.049708135426044464,
 0.9979807734489441,
 1.2156037092208862,
 0.9596575498580933,
 0.7243912816047668,
 2.045924425125122,
 0.3436098098754883,
 1.7106215953826904,
 0.35937026143074036,
 0.7879112958908081,
 0.6920586824417114,
 0.5250598788261414,
 0.9107099175453186,
 1.0807123184204102,
 1.0860090255737305,
 1.0328856706619263,
 1.2514424324035645,
 0.08290626853704453,
 0.9596575498580933,
 0.2896677255630493,
 0.25004541873931885,
 1.029866337776184,
 0.3061467111110687,
 0.9458042979240417,
 0.9429183602333069,
 0.19697941839694977,
 0.21719519793987274,
 0.27168768644332886,
 0.2554975748062134,
 0.22963480651378632,
 0.34251776337623596,
 0.3839860260486603,
 0.8593157529830933,
 0.864760160446167,
 0.47344133257865906,
 0.5390608310699463,
 1.924526333808899,
 1.1563271284103394,
 1.2368268966674805,
 0.1715027242898941,
 0.9596575498580933,
 2.137813091278076,
 0.3629041016101837,
 1.736001968383789,
 1.9738810062408447,
 0.8626371622085571,
 0.6532668471336365,
 0.4636140465736389,
 0.9527161121368408,
 1.1247174739837646,
 1.1320680379867554,
 1.167222023010254,
 1.4093562364578247,
 0.07918576896190643,
 1.924526333808899,
 0.29961133003234863,
 0.23631542921066284,
 1.041368842124939,
 0.3079191744327545,
 0.11354421824216843,
 0.9454419016838074,
 0.2220916599035263,
 0.18270735442638397,
 0.27243098616600037,
 0.28455692529678345,
 0.22796691954135895,
 0.3458220958709717,
 0.38700878620147705,
 0.8904160261154175,
 0.2752673327922821,
 1.9738810062408447,
 0.5503026247024536,
 0.5497167110443115,
 1.0818827152252197,
 0.6485979557037354,
 0.7200310230255127,
 0.049708135426044464,
 2.143386125564575,
 0.3666935861110687,
 1.739219307899475,
 1.6484227180480957,
 0.8784986138343811,
 0.3178224265575409,
 0.24234473705291748,
 0.956663191318512,
 1.2249338626861572,
 1.2315421104431152,
 1.1827014684677124,
 1.4199867248535156,
 0.0855390802025795,
 0.2752673327922821,
 0.2659192681312561,
 0.21446619927883148,
 0.9966477155685425,
 0.30261021852493286,
 0.10452374070882797,
 0.9294785857200623,
 0.14450035989284515,
 0.18121981620788574,
 0.2631380259990692,
 0.27165958285331726,
 0.20280446112155914,
 0.329235702753067,
 0.37825462222099304,
 0.8209134936332703,
 0.8808217644691467,
 1.9355655908584595,
 0.4989796578884125,
 0.525527834892273,
 0.8419976830482483,
 1.924526333808899,
 0.7064990401268005,
 0.8473559021949768,
 2.1138436794281006,
 0.34976351261138916,
 1.722825288772583,
 1.6290391683578491,
 0.8182077407836914,
 0.6445652842521667,
 0.7257094979286194,
 0.9292212724685669,
 1.2002670764923096,
 1.2073462009429932,
 1.0643678903579712,
 1.3049191236495972,
 0.07547403126955032,
 0.8808217644691467,
 0.1686258316040039,
 0.15057426691055298,
 0.9131693243980408,
 0.3047838807106018,
 0.11051282286643982,
 0.9234853982925415,
 0.17730925977230072,
 0.10343598574399948,
 0.24541456997394562,
 0.2488224357366562,
 0.14159072935581207,
 0.3160823881626129,
 0.37810614705085754,
 0.8353131413459778,
 0.049708135426044464,
 1.9189149141311646,
 0.4416227340698242,
 0.46306562423706055,
 0.6751553416252136,
 0.049708135426044464,
 0.7017978429794312,
 0.049708135426044464,
 2.1248722076416016,
 0.3348129391670227,
 1.7315771579742432,
 1.637636661529541,
 0.7378816604614258,
 0.6507152915000916,
 0.7211668491363525,
 0.8993930220603943,
 1.179996132850647,
 1.1827913522720337,
 0.9483506679534912,
 1.2135553359985352,
 0.08009864389896393,
 0.049708135426044464,
 0.29162585735321045,
 0.2311440110206604,
 1.0019994974136353,
 0.2900545597076416,
 0.09923070669174194,
 0.9277050495147705,
 0.24766071140766144,
 0.1905079483985901,
 0.25884220004081726,
 0.2676609754562378,
 0.2113756686449051,
 0.33489781618118286,
 0.37469905614852905,
 0.8637315034866333,
 0.1834801584482193,
 1.952622652053833,
 0.5276255011558533,
 0.5088150501251221,
 0.8207700848579407,
 1.924526333808899,
 0.7045491337776184,
 0.1715027242898941,
 2.1169488430023193,
 0.3553192913532257,
 1.7184748649597168,
 1.623410940170288,
 0.8018119931221008,
 0.7217857241630554,
 0.8072001934051514,
 0.9315654039382935,
 1.1985658407211304,
 1.2037396430969238,
 1.0955076217651367,
 1.3365261554718018,
 0.07810045033693314,
 0.09936454147100449,
 0.2843988537788391,
 0.224129319190979,
 0.9739627838134766,
 0.29442092776298523,
 0.10810764133930206,
 0.9024221897125244,
 0.21570613980293274,
 0.1658022105693817,
 0.26125437021255493,
 0.2701275944709778,
 0.2114921361207962,
 0.33815017342567444,
 0.38028374314308167,
 0.860846996307373,
 0.8808217644691467,
 1.9661701917648315,
 0.5366172790527344,
 0.5194403529167175,
 0.8779125809669495,
 0.2396182268857956,
 0.8350181579589844,
 0.2396182268857956,
 2.1370186805725098,
 0.3586333394050598,
 1.7324014902114868,
 1.6415780782699585,
 0.8236221075057983,
 0.6536813974380493,
 0.6755555868148804,
 0.9497234225273132,
 1.209280252456665,
 1.216010570526123,
 1.164337396621704,
 1.4797621965408325,
 0.07284143567085266,
 0.09589855372905731,
 0.2954607903957367,
 0.22967354953289032,
 0.953351616859436,
 0.2954997420310974,
 0.10941589623689651,
 0.9036650657653809,
 0.23797519505023956,
 0.17362725734710693,
 0.26334819197654724,
 0.2737519145011902,
 0.21101818978786469,
 0.34120550751686096,
 0.38213449716567993,
 0.8788299560546875,
 0.9596575498580933,
 1.9695409536361694,
 0.5484753251075745,
 0.5302969813346863,
 0.9001454710960388,
 0.1715027242898941,
 0.8359003663063049,
 0.9596575498580933,
 2.1397316455841064,
 0.361917108297348,
 1.7342926263809204,
 1.6434733867645264,
 0.8391125798225403,
 0.33684295415878296,
 0.3040230870246887,
 0.9518406391143799,
 1.2223060131072998,
 1.2288371324539185,
 1.1783274412155151,
 1.4872912168502808,
 0.07813754677772522,
 0.09228358417749405,
 0.25990402698516846,
 0.22325697541236877,
 0.9072495102882385,
 0.28872519731521606,
 0.8808217644691467,
 0.8821022510528564,
 0.14805220067501068,
 0.16699598729610443,
 0.2450082153081894,
 0.25457900762557983,
 0.20269401371479034,
 0.31995701789855957,
 0.3676065504550934,
 0.7757319808006287,
 0.049708135426044464,
 1.906736969947815,
 0.5115987658500671,
 0.49701258540153503,
 0.7992445230484009,
 0.6485979557037354,
 0.8090298771858215,
 0.2396182268857956,
 2.1169204711914062,
 0.3390612304210663,
 1.6404308080673218,
 1.7239476442337036,
 0.7931366562843323,
 0.5887452960014343,
 0.6773756742477417,
 0.919990599155426,
 1.1110506057739258,
 1.1207860708236694,
 1.0836793184280396,
 1.4004733562469482,
 0.0793827474117279,
 0.10942330956459045,
 0.2241881936788559,
 0.2300443798303604,
 0.9074889421463013,
 0.2931664288043976,
 1.924526333808899,
 0.8921805620193481,
 0.08026079833507538,
 0.1641838699579239,
 0.25504744052886963,
 0.26247555017471313,
 0.19202563166618347,
 0.33313149213790894,
 0.37804099917411804,
 0.8014106154441833,
 0.2752673327922821,
 1.9415361881256104,
 0.5131494402885437,
 0.5030002593994141,
 0.8100820183753967,
 0.47344133257865906,
 0.8226430416107178,
 0.049708135426044464,
 2.128075122833252,
 0.3530791997909546,
 1.6574612855911255,
 1.7431107759475708,
 0.7880103588104248,
 0.5826531052589417,
 0.6248081922531128,
 0.9310759902000427,
 1.1174596548080444,
 1.124678373336792,
 1.0467172861099243,
 1.4018869400024414,
 0.07966501265764236,
 0.10941991955041885,
 0.20751872658729553,
 0.1915551722049713,
 0.8971952795982361,
 0.28969964385032654,

In [26]:
input['est_uni']=predicciones_uniform
input['est_dis']=predicciones_discriminatory

In [27]:
input

      id_planta        Fecha       phi  Grupo  precio_d   est_uni   est_dis
0             1   2025-04-01  0.083924      1   0.10137  0.095125  0.096977
1             2   2025-04-01  0.262222      5   0.28295  0.273429  0.275267
2             3   2025-04-01  0.275288      5   0.32637  0.286496  0.288333
3             4   2025-04-01  0.260380      5   0.31037  0.271587  0.273426
4             5   2025-04-01  0.968472      4   1.02813  0.979695  0.981495
...         ...          ...       ...    ...       ...       ...       ...
4207         32   2025-09-09  0.779362      4   0.90894  0.790581  0.792391
4208         33   2025-09-09  1.058581      4   1.11735  1.069806  1.071605
4209         34   2025-09-09  0.945489      4   1.01274  0.956712  0.958513
4210         35   2025-09-09  0.969786      4   1.18348  0.981009  0.982809
4211         36   2025-09-09  1.255597      4   1.48540  1.266827  1.268623

[4212 rows x 7 columns]

## Equilibrios

In [11]:
import torch
import torch.nn.functional as F

x = phi_a_tensor_24(1.255597)
with torch.no_grad():
    raw = net_uniform.net(x).reshape(-1)
    inc = F.softplus(raw)
    bid = net_uniform(x).reshape(-1)

print("raw:", raw.item())
print("softplus(raw):", inc.item())
print("bid:", bid.item(), "phi:", x.mean().item(), "bid-phi:", (bid - x.mean()).item())

raw: 0.43513038754463196
softplus(raw): 0.9341952800750732
bid: 1.2742817401885986 phi: 1.2555968761444092 bid-phi: 0.018684864044189453

In [12]:
import torch
import torch.nn.functional as F

x = phi_a_tensor_24(1.255597)
with torch.no_grad():
    raw = net_discriminatory.net(x).reshape(-1)
    inc = F.softplus(raw)
    bid = net_discriminatory(x).reshape(-1)

print("raw:", raw.item())
print("softplus(raw):", inc.item())
print("bid:", bid.item(), "phi:", x.mean().item(), "bid-phi:", (bid - x.mean()).item())

raw: 0.3959486484527588
softplus(raw): 0.910591721534729
bid: 1.2738096714019775 phi: 1.2555968761444092 bid-phi: 0.01821279525756836

## notas:
en maximo da bien, uniform es mas pequeño que discirminatory bien

In [13]:
path_uniform = "symmetric/5redespromedio/nets_best_by_gid_uniform.pt"
saved_nets_uniform = torch.load(path_uniform, map_location="cpu")

gid = 1
net_uniform = PolicyNet(
    input_dim=24,
    hidden=(10,10),
    output_dim=1,
    floor_mode="mean",   # <- igual que en entrenamiento
    min_bid=1e-6         # <- igual que en entrenamiento
)
net_uniform.load_state_dict(saved_nets_uniform[gid], strict=True)
net_uniform.eval() # importante para modo evaluación



path_discriminatory = "symmetric/5redespromedio/nets_best_by_gid_pay_as_bid.pt"
saved_nets_discriminatory = torch.load(path_discriminatory, map_location="cpu")

gid = 1
net_discriminatory = PolicyNet(
    input_dim=24,
    hidden=(10,10),
    output_dim=1,
    floor_mode="mean",   # <- igual que en entrenamiento
    min_bid=1e-6         # <- igual que en entrenamiento
)
net_discriminatory.load_state_dict(saved_nets_discriminatory[gid], strict=True)
net_discriminatory.eval() # importante para modo evaluación


import torch
import torch.nn.functional as F

x = phi_a_tensor_24(1.255597)
with torch.no_grad():
    raw = net_uniform.net(x).reshape(-1)
    inc = F.softplus(raw)
    bid = net_uniform(x).reshape(-1)

print("raw:", raw.item())
print("softplus(raw):", inc.item())
print("bid:", bid.item(), "phi:", x.mean().item(), "bid-phi:", (bid - x.mean()).item())

x = phi_a_tensor_24(1.255597)
with torch.no_grad():
    raw = net_discriminatory.net(x).reshape(-1)
    inc = F.softplus(raw)
    bid = net_discriminatory(x).reshape(-1)

print("raw:", raw.item())
print("softplus(raw):", inc.item())
print("bid:", bid.item(), "phi:", x.mean().item(), "bid-phi:", (bid - x.mean()).item())

raw: 0.2204907089471817
softplus(raw): 0.8094573020935059
bid: 1.2717869281768799 phi: 1.2555968761444092 bid-phi: 0.016190052032470703
raw: 0.3046151101589203
softplus(raw): 0.8570089340209961
bid: 1.272737979888916 phi: 1.2555968761444092 bid-phi: 0.017141103744506836

C:\Users\HP\AppData\Local\Temp\ipykernel_6724\4167848203.py:2: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  saved_nets_uniform = torch.load(path_uniform, map_location="cpu")
C:\Users\HP\AppData\Local\Temp\ipykernel_6724\4167848203.py:18: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  saved_nets_discriminatory = torch.load(path_discriminatory, map_location="cpu")